
//MAIN
#include <Arduino.h>
#include <Nicla_System.h>
#include <FireTimer.h>

//BLE
#include <Arduino_BHY2.h>
#include <ArduinoBLE.h>

//LOAD CELL
#include <HX711.h>

//LED
#include <NiclaSenseNeoPixel.h>



//LOAD CELL
#define LOAD_CELL_A_DOUT_PIN 1
#define LOAD_CELL_A_SCK_PIN 2
#define LOAD_CELL_B_DOUT_PIN 3
#define LOAD_CELL_B_SCK_PIN 4
#define LOAD_CELL_CALIBRATION_FACTOR 100
#define LOAD_CELL_DATA_SIZE 7
#define LOAD_CELL_DATA_DEFAULT_VALUE "P;00.00"

//BLE
//Local name
#define BLE_LOCAL_NAME_PREFIX	"RS23001"
#define FW_VERSION	"1.1"
#define HW_VERSION	"1.1"

#define AUTHENTICATION_CHARATERISTIC_SIZE	50	//50 byte

//SHOCK DETECTION
#define SHOCK_THRESHOLD 700
#define SHOCK_DEBOUNCE_TIME 200
#define SHOCK_NUM_SAMPLE 10
#define SHOCK_SCALE_VALUE 10
#define SHOCK_DATA_SIZE 16
#define SHOCK_DATA_DEFAULT_VALUE "U;0000;0000;0000"

//BATTERY
#define BATTERY_FREQ_DATA_SEND 60   //SECONDI
#define BATTERY_DATA_SIZE 5
#define BATTERY_DATA_DEFAULT_VALUE "B;000"

//REQUEST
#define REQUEST_DATA_SIZE 1
#define REQUEST_DATA_DEFAULT_VALUE ""

//LED
#define LED_NUM 1
#define LED_COLOR_RED 0
#define LED_COLOR_GREEN 1
#define LED_COLOR_BLUE 2

//DEBUG
#define MAIN_DEBUG_
#define BATTERY_DEBUG_
#define BLUETOOTH_DEBUG_
#define LOAD_CELL_DEBUG_
#define SHOCK_DEBUG_
