

#define DEBUG Serial

//LOAD CELL
#define LOADCELL_A_DOUT_PIN 1
#define LOADCELL_A_SCK_PIN 2
#define LOADCELL_B_DOUT_PIN 3
#define LOADCELL_B_SCK_PIN 4
#define LOADCELL_CALIBRATION_FACTOR 100

//BLE
//Local name
#define BLE_LOCAL_NAME_PREFIX	"RS23001"
#define FW_VERSION	"1.1"
#define HW_VERSION	"1.1"

#define AUTHENTICATION_CHARATERISTIC_SIZE	50	//50 byte

